### ISSUE TITLE
运行docker-compose 遇到的一些问题。希望你解答

### ISSUE THREAD

**Issue by ZRothschild** [CA17/TeamsACS#10]
当我 运行  docker-compose  up  -f docker-compose.yaml 的时候会报错误数据库拒绝连接，当时我本地可以连接上 qsql

> docker-compose.yaml
```yaml

version: "2"
services:
  pgdb:
    image: timescale/timescaledb:latest-pg14
    container_name: "pgdb"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: teamsacs
      POSTGRES_USER: teamsacs
      POSTGRES_PASSWORD: teamsacs
    volumes:
      - /data/pgdata:/var/lib/postgresql/data
    networks:
      - teamsacs_network
  teamsacs:
    depends_on:
      - pgdb
    image: ca17/teamsacs:latest
    container_name: "teamsacs"
    restart: always
    ports:
      - 9090:8080
      - 8000
      - 8106
      - 8107
      - 8108/udp
    expose:
      - 8000
      - 8106
      - 8107
      - 8108/udp
    volumes:
      - /data/teamsacs:/var/teamsacs
    environment:
      - GODEBUG=x509ignoreCN=0
      - TEAMSACS_WEB_DEBUG=1
      - TEAMSACS_SECRET=9b6de5cc-xxxx-xxxx-xxx-0f568ac9da37
    networks:
      - teamsacs_network
networks:
  teamsacs_network:
```

![image](https://user-images.githubusercontent.com/19706618/168216406-9f2eae4d-bdab-4e5f-95d2-e405caef6a68.png)

![image](https://user-images.githubusercontent.com/19706618/168216456-af12661a-20f8-4363-a07c-3c47ca21dfb8.png)

管理端 控制面板（control panel） 的用户名称与密码是啥呢？

![image](https://user-images.githubusercontent.com/19706618/168216568-32751939-6e55-4988-8378-2646ed66a614.png)
